More clever `meet` script

diff --git a/dotfiles/homies/bin/meet b/dotfiles/homies/bin/meet
--- a/dotfiles/homies/bin/meet
+++ b/dotfiles/homies/bin/meet
@@ -1,8 +1,19 @@
 #!/usr/bin/env bash
 
-URL=https://meet.google.com/zhw-huyd-oam
-echo -n "$URL" | clipit
+url=https://meet.google.com/zhw-huyd-oam
+echo -n "$url" | clipit
 
-# For some reason, my "Honor" profile is actually set up as "Profile 9"? I
-# found this by navigating to chrome://version/.
-chromium --profile-directory="Profile 9" --app="$URL"
+profile_email=jeremy@joinhonor.com
+
+# Search all chromium profiles to find my "Honor" profile. You can manually
+# check which profile you're using by navigating to chrome://version/.
+for profile in "$HOME/.config/chromium/Profile "*; do
+    if [ "$(jq --raw-output '.account_info[0].email' "$profile/Preferences")" = "$profile_email" ]; then
+        echo "Found $profile_email in profile $profile"
+        chromium --profile-directory="$(basename "$profile")" --app="$url"
+        exit 0
+    fi
+done
+
+echo "Could not find a chromium profile for $profile_email" >/dev/stderr
+exit 1
